#include "parser_helper.h"
#include "../common/error.h"
#include "../common/memory.h"
#include "parser.h"   /* generated by Lemon */
#include <stdlib.h>
#include <string.h>

void *ParseAlloc(void *(*mallocProc)(size_t));
void Parse(void *parser, int tokenType, Token token, ParseState *ps);
void ParseFree(void *parser, void (*freeProc)(void *));

/* -----------------------------------------------------------------------
 * Parse driver
 * Feeds tokens produced by the lexer into the Lemon-generated parser.
 * ----------------------------------------------------------------------- */
AstNode *parse_program(const char *source) {
    Lexer      lex;
    ParseState ps = { NULL, 0 };

    lexer_init(&lex, source);

    void *parser = ParseAlloc(cimple_malloc);

    for (;;) {
        Token tok = lexer_next(&lex);

        if (tok.type == TOK_ERROR)
            break;

        Parse(parser, tok.type, tok, &ps);

        if (tok.type == TOK_EOF) {
            break;
        }
    }

    ParseFree(parser, free);
    return ps.root;
}
