#include "parser_helper.h"
#include "../common/error.h"
#include "../common/memory.h"
#include "parser.h"   /* generated by Lemon */
#include <stdlib.h>
#include <string.h>

/* -----------------------------------------------------------------------
 * Parse driver
 * Feeds tokens produced by the lexer into the Lemon-generated parser.
 * ----------------------------------------------------------------------- */
AstNode *parse_program(const char *source) {
    Lexer      lex;
    ParseState ps = { NULL, 0 };

    lexer_init(&lex, source);

    void *parser = ParseAlloc(cimple_malloc);

    for (;;) {
        Token tok = lexer_next(&lex);
        Parse(parser, tok.type, tok, &ps);

        if (tok.type == TOK_EOF) {
            Parse(parser, 0, tok, &ps);
            break;
        }
        if (tok.type == TOK_ERROR)
            break;
    }

    ParseFree(parser, free);
    return ps.root;
}
