#include "parser_helper.h"
#include "../common/error.h"
#include "../common/memory.h"
#include "parser.h"   /* generated by Lemon */
#include <stdlib.h>
#include <string.h>

void *ParseAlloc(void *(*mallocProc)(size_t));
void Parse(void *parser, int tokenType, Token token, ParseState *ps);
void ParseFree(void *parser, void (*freeProc)(void *));

int parse_state_has_struct(const ParseState *ps, const char *name) {
    for (ParseStructName *it = ps->struct_names; it; it = it->next)
        if (strcmp(it->name, name) == 0) return 1;
    return 0;
}

int parse_state_has_type_name(const ParseState *ps, const char *name) {
    return parse_state_has_struct(ps, name);
}

void parse_state_add_struct(ParseState *ps, const char *name) {
    if (parse_state_has_struct(ps, name)) return;
    ParseStructName *entry = ALLOC(ParseStructName);
    entry->name = cimple_strdup(name);
    entry->next = ps->struct_names;
    ps->struct_names = entry;
}

void parse_state_free(ParseState *ps) {
    ParseStructName *it = ps->struct_names;
    while (it) {
        ParseStructName *next = it->next;
        free(it->name);
        free(it);
        it = next;
    }
    ps->struct_names = NULL;
}

static void precollect_struct_names(ParseState *ps, const char *source) {
    Lexer lex;
    TokenType prev_type = TOK_EOF;
    lexer_init(&lex, source);
    for (;;) {
        Token tok = lexer_next(&lex);
        if (tok.type == TOK_ERROR)
            break;
        if ((prev_type == TOK_KW_STRUCTURE || prev_type == TOK_KW_UNION) && tok.type == TOK_IDENT)
            parse_state_add_struct(ps, tok.v.sval);
        prev_type = tok.type;
        if (tok.type == TOK_IDENT || tok.type == TOK_STRING_LIT)
            free(tok.v.sval);
        if (tok.type == TOK_EOF)
            break;
    }
}

/* -----------------------------------------------------------------------
 * Parse driver
 * Feeds tokens produced by the lexer into the Lemon-generated parser.
 * ----------------------------------------------------------------------- */
AstNode *parse_program(const char *source) {
    Lexer      lex;
    ParseState ps = { NULL, 0, TOK_EOF, 0, 0, NULL };
    TokenType prev_type = TOK_EOF;

    precollect_struct_names(&ps, source);
    lexer_init(&lex, source);

    void *parser = ParseAlloc(cimple_malloc);

    for (;;) {
        Token tok = lexer_next(&lex);

        if (prev_type != TOK_KW_STRUCTURE && prev_type != TOK_KW_UNION &&
            tok.type == TOK_IDENT && parse_state_has_type_name(&ps, tok.v.sval))
            tok.type = TOK_TYPE_IDENT;

        if (tok.type == TOK_ERROR)
            break;

        Parse(parser, tok.type, tok, &ps);

        ps.last_token_type = tok.type;
        ps.last_token_line = tok.line;
        ps.last_token_col = tok.col;
        prev_type = tok.type;

        if (tok.type == TOK_EOF) {
            break;
        }
    }

    ParseFree(parser, free);
    parse_state_free(&ps);
    return ps.root;
}
