export interface BuiltinParam { name: string; type: string; }
export interface BuiltinFunction {
    name: string;
    signature: string;
    doc: string;
    params: BuiltinParam[];
    returnType: string;
}
export interface BuiltinConstant { name: string; type: string; value: string; doc: string; }
export interface BuiltinType { name: string; fields: {name:string;type:string}[]; inits: string[]; }

export const BUILTIN_FUNCTIONS: BuiltinFunction[] = [
    { name:'print', signature:'void print(string value)', doc:'Print to stdout', params:[{name:'value',type:'string'}], returnType:'void' },
    { name:'printErr', signature:'void printErr(string value)', doc:'Print to stderr', params:[{name:'value',type:'string'}], returnType:'void' },
    { name:'exit', signature:'void exit(int code)', doc:'Exit the program with the given code', params:[{name:'code',type:'int'}], returnType:'void' },
    { name:'format', signature:'string format(string template, ...)', doc:'Format a string with placeholders {}', params:[{name:'template',type:'string'}], returnType:'string' },
    { name:'toString', signature:'string toString(int|float|bool value)', doc:'Convert a value to its string representation', params:[{name:'value',type:'int'}], returnType:'string' },
    { name:'toInt', signature:'int toInt(string|float|bool value)', doc:'Convert a value to int', params:[{name:'value',type:'string'}], returnType:'int' },
    { name:'toFloat', signature:'float toFloat(string|int|bool value)', doc:'Convert a value to float', params:[{name:'value',type:'string'}], returnType:'float' },
    { name:'toBool', signature:'bool toBool(string|int|float value)', doc:'Convert a value to bool', params:[{name:'value',type:'string'}], returnType:'bool' },
    { name:'count', signature:'int count(T[] array)', doc:'Number of elements in an array', params:[{name:'array',type:'T[]'}], returnType:'int' },
    { name:'append', signature:'void append(T[] array, T value)', doc:'Append a value to an array', params:[{name:'array',type:'T[]'},{name:'value',type:'T'}], returnType:'void' },
    { name:'pop', signature:'T pop(T[] array)', doc:'Remove and return the last element', params:[{name:'array',type:'T[]'}], returnType:'T' },
    { name:'insert', signature:'void insert(T[] array, int index, T value)', doc:'Insert a value at index', params:[{name:'array',type:'T[]'},{name:'index',type:'int'},{name:'value',type:'T'}], returnType:'void' },
    { name:'remove', signature:'void remove(T[] array, int index)', doc:'Remove element at index', params:[{name:'array',type:'T[]'},{name:'index',type:'int'}], returnType:'void' },
    { name:'concat', signature:'T[] concat(T[] a, T[] b)', doc:'Concatenate two arrays', params:[{name:'a',type:'T[]'},{name:'b',type:'T[]'}], returnType:'T[]' },
    { name:'sort', signature:'void sort(T[] array)', doc:'Sort array in place', params:[{name:'array',type:'T[]'}], returnType:'void' },
    { name:'reverse', signature:'void reverse(T[] array)', doc:'Reverse array in place', params:[{name:'array',type:'T[]'}], returnType:'void' },
    { name:'slice', signature:'T[] slice(T[] array, int start, int end)', doc:'Extract a sub-array', params:[{name:'array',type:'T[]'},{name:'start',type:'int'},{name:'end',type:'int'}], returnType:'T[]' },
    { name:'contains', signature:'bool contains(string s, string sub)', doc:'Check if string contains substring', params:[{name:'s',type:'string'},{name:'sub',type:'string'}], returnType:'bool' },
    { name:'indexOf', signature:'int indexOf(string s, string sub)', doc:'First index of substring, -1 if not found', params:[{name:'s',type:'string'},{name:'sub',type:'string'}], returnType:'int' },
    { name:'lastIndexOf', signature:'int lastIndexOf(string s, string sub)', doc:'Last index of substring, -1 if not found', params:[{name:'s',type:'string'},{name:'sub',type:'string'}], returnType:'int' },
    { name:'startsWith', signature:'bool startsWith(string s, string prefix)', doc:'Check if string starts with prefix', params:[{name:'s',type:'string'},{name:'prefix',type:'string'}], returnType:'bool' },
    { name:'endsWith', signature:'bool endsWith(string s, string suffix)', doc:'Check if string ends with suffix', params:[{name:'s',type:'string'},{name:'suffix',type:'string'}], returnType:'bool' },
    { name:'replace', signature:'string replace(string s, string from, string to)', doc:'Replace first occurrence', params:[{name:'s',type:'string'},{name:'from',type:'string'},{name:'to',type:'string'}], returnType:'string' },
    { name:'replaceAll', signature:'string replaceAll(string s, string from, string to)', doc:'Replace all occurrences', params:[{name:'s',type:'string'},{name:'from',type:'string'},{name:'to',type:'string'}], returnType:'string' },
    { name:'trim', signature:'string trim(string s)', doc:'Remove leading and trailing whitespace', params:[{name:'s',type:'string'}], returnType:'string' },
    { name:'trimStart', signature:'string trimStart(string s)', doc:'Remove leading whitespace', params:[{name:'s',type:'string'}], returnType:'string' },
    { name:'trimEnd', signature:'string trimEnd(string s)', doc:'Remove trailing whitespace', params:[{name:'s',type:'string'}], returnType:'string' },
    { name:'upper', signature:'string upper(string s)', doc:'Convert to uppercase', params:[{name:'s',type:'string'}], returnType:'string' },
    { name:'lower', signature:'string lower(string s)', doc:'Convert to lowercase', params:[{name:'s',type:'string'}], returnType:'string' },
    { name:'repeat', signature:'string repeat(string s, int n)', doc:'Repeat string n times', params:[{name:'s',type:'string'},{name:'n',type:'int'}], returnType:'string' },
    { name:'padLeft', signature:'string padLeft(string s, int width, string pad)', doc:'Pad string on the left', params:[{name:'s',type:'string'},{name:'width',type:'int'},{name:'pad',type:'string'}], returnType:'string' },
    { name:'padRight', signature:'string padRight(string s, int width, string pad)', doc:'Pad string on the right', params:[{name:'s',type:'string'},{name:'width',type:'int'},{name:'pad',type:'string'}], returnType:'string' },
    { name:'split', signature:'string[] split(string s, string sep)', doc:'Split string by separator', params:[{name:'s',type:'string'},{name:'sep',type:'string'}], returnType:'string[]' },
    { name:'join', signature:'string join(string[] parts, string sep)', doc:'Join array of strings with separator', params:[{name:'parts',type:'string[]'},{name:'sep',type:'string'}], returnType:'string' },
    { name:'substring', signature:'string substring(string s, int start, int end)', doc:'Extract substring', params:[{name:'s',type:'string'},{name:'start',type:'int'},{name:'end',type:'int'}], returnType:'string' },
    { name:'charAt', signature:'string charAt(string s, int index)', doc:'Character at index', params:[{name:'s',type:'string'},{name:'index',type:'int'}], returnType:'string' },
    { name:'byteAt', signature:'byte byteAt(string s, int index)', doc:'Byte value at index', params:[{name:'s',type:'string'},{name:'index',type:'int'}], returnType:'byte' },
    { name:'length', signature:'int length(string s)', doc:'Byte length of string', params:[{name:'s',type:'string'}], returnType:'int' },
    { name:'glyph', signature:'string glyph(string s, int index)', doc:'Unicode codepoint at glyph index', params:[{name:'s',type:'string'},{name:'index',type:'int'}], returnType:'string' },
    { name:'glyphCount', signature:'int glyphCount(string s)', doc:'Number of Unicode codepoints', params:[{name:'s',type:'string'}], returnType:'int' },
    { name:'isBlank', signature:'bool isBlank(string s)', doc:'True if string is empty or whitespace only', params:[{name:'s',type:'string'}], returnType:'bool' },
    { name:'isInt', signature:'bool isInt(string s)', doc:'True if string is a valid integer', params:[{name:'s',type:'string'}], returnType:'bool' },
    { name:'isFloat', signature:'bool isFloat(string s)', doc:'True if string is a valid float', params:[{name:'s',type:'string'}], returnType:'bool' },
    { name:'isBool', signature:'bool isBool(string s)', doc:'True if string is "true" or "false"', params:[{name:'s',type:'string'}], returnType:'bool' },
    { name:'sqrt', signature:'float sqrt(float x)', doc:'Square root', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'pow', signature:'float pow(float base, float exp)', doc:'base raised to exp', params:[{name:'base',type:'float'},{name:'exp',type:'float'}], returnType:'float' },
    { name:'abs', signature:'int abs(int x)', doc:'Absolute value (int)', params:[{name:'x',type:'int'}], returnType:'int' },
    { name:'floor', signature:'int floor(float x)', doc:'Floor of float', params:[{name:'x',type:'float'}], returnType:'int' },
    { name:'ceil', signature:'int ceil(float x)', doc:'Ceiling of float', params:[{name:'x',type:'float'}], returnType:'int' },
    { name:'round', signature:'int round(float x)', doc:'Round to nearest int', params:[{name:'x',type:'float'}], returnType:'int' },
    { name:'trunc', signature:'int trunc(float x)', doc:'Truncate to int', params:[{name:'x',type:'float'}], returnType:'int' },
    { name:'log', signature:'float log(float x)', doc:'Natural logarithm', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'log2', signature:'float log2(float x)', doc:'Base-2 logarithm', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'log10', signature:'float log10(float x)', doc:'Base-10 logarithm', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'exp', signature:'float exp(float x)', doc:'e^x', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'sin', signature:'float sin(float x)', doc:'Sine (radians)', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'cos', signature:'float cos(float x)', doc:'Cosine (radians)', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'tan', signature:'float tan(float x)', doc:'Tangent (radians)', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'asin', signature:'float asin(float x)', doc:'Arc sine', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'acos', signature:'float acos(float x)', doc:'Arc cosine', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'atan', signature:'float atan(float x)', doc:'Arc tangent', params:[{name:'x',type:'float'}], returnType:'float' },
    { name:'atan2', signature:'float atan2(float y, float x)', doc:'Two-argument arc tangent', params:[{name:'y',type:'float'},{name:'x',type:'float'}], returnType:'float' },
    { name:'min', signature:'int min(int a, int b)', doc:'Minimum of two values', params:[{name:'a',type:'int'},{name:'b',type:'int'}], returnType:'int' },
    { name:'max', signature:'int max(int a, int b)', doc:'Maximum of two values', params:[{name:'a',type:'int'},{name:'b',type:'int'}], returnType:'int' },
    { name:'clamp', signature:'int clamp(int x, int lo, int hi)', doc:'Clamp x between lo and hi', params:[{name:'x',type:'int'},{name:'lo',type:'int'},{name:'hi',type:'int'}], returnType:'int' },
    { name:'approxEqual', signature:'bool approxEqual(float a, float b, float epsilon)', doc:'True if |a-b| <= epsilon', params:[{name:'a',type:'float'},{name:'b',type:'float'},{name:'epsilon',type:'float'}], returnType:'bool' },
    { name:'isFinite', signature:'bool isFinite(float x)', doc:'True if x is finite', params:[{name:'x',type:'float'}], returnType:'bool' },
    { name:'isInfinite', signature:'bool isInfinite(float x)', doc:'True if x is infinite', params:[{name:'x',type:'float'}], returnType:'bool' },
    { name:'isNaN', signature:'bool isNaN(float x)', doc:'True if x is NaN', params:[{name:'x',type:'float'}], returnType:'bool' },
    { name:'isPositiveInfinity', signature:'bool isPositiveInfinity(float x)', doc:'True if x is +Inf', params:[{name:'x',type:'float'}], returnType:'bool' },
    { name:'isNegativeInfinity', signature:'bool isNegativeInfinity(float x)', doc:'True if x is -Inf', params:[{name:'x',type:'float'}], returnType:'bool' },
    { name:'safeDiv', signature:'int safeDiv(int a, int b, int fallback)', doc:'a/b or fallback if b==0', params:[{name:'a',type:'int'},{name:'b',type:'int'},{name:'fallback',type:'int'}], returnType:'int' },
    { name:'safeMod', signature:'int safeMod(int a, int b, int fallback)', doc:'a%b or fallback if b==0', params:[{name:'a',type:'int'},{name:'b',type:'int'},{name:'fallback',type:'int'}], returnType:'int' },
    { name:'rand', signature:'float rand()', doc:'Random float in [0, 1)', params:[], returnType:'float' },
    { name:'randInt', signature:'int randInt(int lo, int hi)', doc:'Random int in [lo, hi]', params:[{name:'lo',type:'int'},{name:'hi',type:'int'}], returnType:'int' },
    { name:'assert', signature:'void assert(bool condition, string message)', doc:'Throw RuntimeException if condition is false', params:[{name:'condition',type:'bool'},{name:'message',type:'string'}], returnType:'void' },
    { name:'readFile', signature:'string readFile(string path)', doc:'Read entire file as string', params:[{name:'path',type:'string'}], returnType:'string' },
    { name:'writeFile', signature:'void writeFile(string path, string content)', doc:'Write string to file', params:[{name:'path',type:'string'},{name:'content',type:'string'}], returnType:'void' },
    { name:'appendFile', signature:'void appendFile(string path, string content)', doc:'Append string to file', params:[{name:'path',type:'string'},{name:'content',type:'string'}], returnType:'void' },
    { name:'fileExists', signature:'bool fileExists(string path)', doc:'True if file exists', params:[{name:'path',type:'string'}], returnType:'bool' },
    { name:'deleteFile', signature:'void deleteFile(string path)', doc:'Delete a file', params:[{name:'path',type:'string'}], returnType:'void' },
    { name:'copyFile', signature:'void copyFile(string src, string dst)', doc:'Copy file from src to dst', params:[{name:'src',type:'string'},{name:'dst',type:'string'}], returnType:'void' },
    { name:'moveFile', signature:'void moveFile(string src, string dst)', doc:'Move/rename file', params:[{name:'src',type:'string'},{name:'dst',type:'string'}], returnType:'void' },
    { name:'listDir', signature:'string[] listDir(string path)', doc:'List directory entries', params:[{name:'path',type:'string'}], returnType:'string[]' },
    { name:'makeDir', signature:'void makeDir(string path)', doc:'Create directory', params:[{name:'path',type:'string'}], returnType:'void' },
    { name:'makeDirAll', signature:'void makeDirAll(string path)', doc:'Create directory and all parents', params:[{name:'path',type:'string'}], returnType:'void' },
    { name:'tempPath', signature:'string tempPath(string prefix)', doc:'Create a unique temp file path', params:[{name:'prefix',type:'string'}], returnType:'string' },
    { name:'pathJoin', signature:'string pathJoin(string a, string b)', doc:'Join path segments', params:[{name:'a',type:'string'},{name:'b',type:'string'}], returnType:'string' },
    { name:'pathDir', signature:'string pathDir(string path)', doc:'Directory part of path', params:[{name:'path',type:'string'}], returnType:'string' },
    { name:'pathBase', signature:'string pathBase(string path)', doc:'Base name of path', params:[{name:'path',type:'string'}], returnType:'string' },
    { name:'pathExt', signature:'string pathExt(string path)', doc:'Extension of path (with dot)', params:[{name:'path',type:'string'}], returnType:'string' },
    { name:'pathIsAbs', signature:'bool pathIsAbs(string path)', doc:'True if path is absolute', params:[{name:'path',type:'string'}], returnType:'bool' },
    { name:'exec', signature:'ExecResult exec(string[] argv)', doc:'Run external command', params:[{name:'argv',type:'string[]'}], returnType:'ExecResult' },
    { name:'env', signature:'string env(string name)', doc:'Get environment variable (throws if unset)', params:[{name:'name',type:'string'}], returnType:'string' },
    { name:'envDefault', signature:'string envDefault(string name, string fallback)', doc:'Get environment variable with fallback', params:[{name:'name',type:'string'},{name:'fallback',type:'string'}], returnType:'string' },
    { name:'now', signature:'int now()', doc:'Current Unix timestamp in seconds', params:[], returnType:'int' },
    { name:'sleep', signature:'void sleep(int milliseconds)', doc:'Pause execution', params:[{name:'milliseconds',type:'int'}], returnType:'void' },
    { name:'formatDate', signature:'string formatDate(int epoch, string format)', doc:'Format epoch as date string', params:[{name:'epoch',type:'int'},{name:'format',type:'string'}], returnType:'string' },
    { name:'parseDate', signature:'int parseDate(string date, string format)', doc:'Parse date string to epoch', params:[{name:'date',type:'string'},{name:'format',type:'string'}], returnType:'int' },
    { name:'makeEpoch', signature:'int makeEpoch(int year, int month, int day)', doc:'Create epoch from date parts', params:[{name:'year',type:'int'},{name:'month',type:'int'},{name:'day',type:'int'}], returnType:'int' },
    { name:'epochYear', signature:'int epochYear(int epoch)', doc:'Year from epoch', params:[{name:'epoch',type:'int'}], returnType:'int' },
    { name:'epochMonth', signature:'int epochMonth(int epoch)', doc:'Month from epoch (1-12)', params:[{name:'epoch',type:'int'}], returnType:'int' },
    { name:'epochDay', signature:'int epochDay(int epoch)', doc:'Day of month from epoch', params:[{name:'epoch',type:'int'}], returnType:'int' },
    { name:'epochHour', signature:'int epochHour(int epoch)', doc:'Hour from epoch (0-23)', params:[{name:'epoch',type:'int'}], returnType:'int' },
    { name:'epochMinute', signature:'int epochMinute(int epoch)', doc:'Minute from epoch (0-59)', params:[{name:'epoch',type:'int'}], returnType:'int' },
    { name:'epochSecond', signature:'int epochSecond(int epoch)', doc:'Second from epoch (0-59)', params:[{name:'epoch',type:'int'}], returnType:'int' },
    { name:'readBytes', signature:'byte[] readBytes(string path)', doc:'Read file as byte array', params:[{name:'path',type:'string'}], returnType:'byte[]' },
    { name:'writeBytes', signature:'void writeBytes(string path, byte[] data)', doc:'Write byte array to file', params:[{name:'path',type:'string'},{name:'data',type:'byte[]'}], returnType:'void' },
    { name:'appendBytes', signature:'void appendBytes(string path, byte[] data)', doc:'Append byte array to file', params:[{name:'path',type:'string'},{name:'data',type:'byte[]'}], returnType:'void' },
    { name:'regexMatch', signature:'RegExpMatch regexMatch(RegExp re, string s)', doc:'Match regex against string', params:[{name:'re',type:'RegExp'},{name:'s',type:'string'}], returnType:'RegExpMatch' },
    { name:'regexTest', signature:'bool regexTest(RegExp re, string s)', doc:'Test if regex matches string', params:[{name:'re',type:'RegExp'},{name:'s',type:'string'}], returnType:'bool' },
    { name:'regexFindAll', signature:'RegExpMatch[] regexFindAll(RegExp re, string s)', doc:'Find all matches', params:[{name:'re',type:'RegExp'},{name:'s',type:'string'}], returnType:'RegExpMatch[]' },
    { name:'regexReplace', signature:'string regexReplace(RegExp re, string s, string repl)', doc:'Replace first match', params:[{name:'re',type:'RegExp'},{name:'s',type:'string'},{name:'repl',type:'string'}], returnType:'string' },
    { name:'regexReplaceAll', signature:'string regexReplaceAll(RegExp re, string s, string repl)', doc:'Replace all matches', params:[{name:'re',type:'RegExp'},{name:'s',type:'string'},{name:'repl',type:'string'}], returnType:'string' },
    { name:'mapKeys', signature:'K[] mapKeys(V[K] m)', doc:'All keys of map', params:[{name:'m',type:'V[K]'}], returnType:'K[]' },
    { name:'mapValues', signature:'V[] mapValues(V[K] m)', doc:'All values of map', params:[{name:'m',type:'V[K]'}], returnType:'V[]' },
    { name:'mapContains', signature:'bool mapContains(V[K] m, K key)', doc:'True if map contains key', params:[{name:'m',type:'V[K]'},{name:'key',type:'K'}], returnType:'bool' },
    { name:'mapRemove', signature:'void mapRemove(V[K] m, K key)', doc:'Remove key from map', params:[{name:'m',type:'V[K]'},{name:'key',type:'K'}], returnType:'void' },
    { name:'mapCount', signature:'int mapCount(V[K] m)', doc:'Number of entries in map', params:[{name:'m',type:'V[K]'}], returnType:'int' },
    { name:'termInit', signature:'void termInit()', doc:'Initialize terminal for TUI mode', params:[], returnType:'void' },
    { name:'termRestore', signature:'void termRestore()', doc:'Restore terminal to normal mode', params:[], returnType:'void' },
    { name:'termClear', signature:'void termClear()', doc:'Clear the terminal screen', params:[], returnType:'void' },
    { name:'termClearLine', signature:'void termClearLine()', doc:'Clear current line', params:[], returnType:'void' },
    { name:'termMoveTo', signature:'void termMoveTo(int row, int col)', doc:'Move cursor to position', params:[{name:'row',type:'int'},{name:'col',type:'int'}], returnType:'void' },
    { name:'termSetColor', signature:'void termSetColor(int fg, int bg)', doc:'Set foreground/background color', params:[{name:'fg',type:'int'},{name:'bg',type:'int'}], returnType:'void' },
    { name:'termResetColor', signature:'void termResetColor()', doc:'Reset to default colors', params:[], returnType:'void' },
    { name:'termBold', signature:'void termBold()', doc:'Enable bold text', params:[], returnType:'void' },
    { name:'termDim', signature:'void termDim()', doc:'Enable dim text', params:[], returnType:'void' },
    { name:'termUnderline', signature:'void termUnderline()', doc:'Enable underline', params:[], returnType:'void' },
    { name:'termReset', signature:'void termReset()', doc:'Reset all text attributes', params:[], returnType:'void' },
    { name:'termGetSize', signature:'TerminalSize termGetSize()', doc:'Get terminal dimensions', params:[], returnType:'TerminalSize' },
    { name:'termReadKey', signature:'KeyEvent termReadKey()', doc:'Read a key press event', params:[], returnType:'KeyEvent' },
    { name:'shellInputBox', signature:'string shellInputBox(string title, string prompt, string initialValue)', doc:'Show a text input dialog', params:[{name:'title',type:'string'},{name:'prompt',type:'string'},{name:'initialValue',type:'string'}], returnType:'string' },
];

export const BUILTIN_CONSTANTS: BuiltinConstant[] = [
    { name:'EOL', type:'string', value:'"\\n" (POSIX) / "\\r\\n" (Windows)', doc:'Platform line ending' },
    { name:'INT_MAX', type:'int', value:'9223372036854775807', doc:'Largest int value' },
    { name:'INT_MIN', type:'int', value:'-9223372036854775808', doc:'Smallest int value' },
    { name:'INT_SIZE', type:'int', value:'8', doc:'Size of int in bytes' },
    { name:'FLOAT_SIZE', type:'int', value:'8', doc:'Size of float in bytes' },
    { name:'FLOAT_DIG', type:'int', value:'15', doc:'Significant decimal digits in float' },
    { name:'FLOAT_EPSILON', type:'float', value:'2.220446e-16', doc:'Smallest float such that 1.0+x != 1.0' },
    { name:'FLOAT_MIN', type:'float', value:'2.225074e-308', doc:'Smallest positive normalized float' },
    { name:'FLOAT_MAX', type:'float', value:'1.797693e+308', doc:'Largest positive float' },
    { name:'M_PI', type:'float', value:'3.141592653589793', doc:'π' },
    { name:'M_E', type:'float', value:'2.718281828459045', doc:"e (Euler's number)" },
    { name:'M_TAU', type:'float', value:'6.283185307179586', doc:'τ = 2π' },
    { name:'M_SQRT2', type:'float', value:'1.4142135623730951', doc:'√2' },
    { name:'M_LN2', type:'float', value:'0.6931471805599453', doc:'ln 2' },
    { name:'M_LN10', type:'float', value:'2.302585092994046', doc:'ln 10' },
    { name:'KEY_NONE', type:'int', value:'0', doc:'No key event' },
    { name:'KEY_CHAR', type:'int', value:'1', doc:'Regular character key' },
    { name:'KEY_ENTER', type:'int', value:'2', doc:'Enter key' },
    { name:'KEY_ESC', type:'int', value:'3', doc:'Escape key' },
    { name:'KEY_TAB', type:'int', value:'4', doc:'Tab key' },
    { name:'KEY_BACKSPACE', type:'int', value:'5', doc:'Backspace key' },
    { name:'KEY_DELETE', type:'int', value:'6', doc:'Delete key' },
    { name:'KEY_UP', type:'int', value:'7', doc:'Up arrow' },
    { name:'KEY_DOWN', type:'int', value:'8', doc:'Down arrow' },
    { name:'KEY_LEFT', type:'int', value:'9', doc:'Left arrow' },
    { name:'KEY_RIGHT', type:'int', value:'10', doc:'Right arrow' },
    { name:'KEY_HOME', type:'int', value:'11', doc:'Home key' },
    { name:'KEY_END', type:'int', value:'12', doc:'End key' },
    { name:'KEY_PAGE_UP', type:'int', value:'13', doc:'Page Up key' },
    { name:'KEY_PAGE_DOWN', type:'int', value:'14', doc:'Page Down key' },
    { name:'KEY_RESIZE', type:'int', value:'15', doc:'Terminal resize event' },
    { name:'TERM_COLOR_DEFAULT', type:'int', value:'-1', doc:'Default terminal color' },
    { name:'TERM_COLOR_BLACK', type:'int', value:'0', doc:'Black' },
    { name:'TERM_COLOR_RED', type:'int', value:'1', doc:'Red' },
    { name:'TERM_COLOR_GREEN', type:'int', value:'2', doc:'Green' },
    { name:'TERM_COLOR_YELLOW', type:'int', value:'3', doc:'Yellow' },
    { name:'TERM_COLOR_BLUE', type:'int', value:'4', doc:'Blue' },
    { name:'TERM_COLOR_MAGENTA', type:'int', value:'5', doc:'Magenta' },
    { name:'TERM_COLOR_CYAN', type:'int', value:'6', doc:'Cyan' },
    { name:'TERM_COLOR_WHITE', type:'int', value:'7', doc:'White' },
];

export const BUILTIN_TYPES: BuiltinType[] = [
    { name:'Exception', fields:[{name:'message',type:'string'}], inits:['_init(string message)'] },
    { name:'RuntimeException', fields:[{name:'message',type:'string'}], inits:['_init(string message)'] },
    { name:'IoException', fields:[{name:'path',type:'string'},{name:'message',type:'string'}], inits:['_init(string message)','_init(string path, string message)'] },
    { name:'RegExpException', fields:[{name:'message',type:'string'}], inits:['_init(string message)'] },
    { name:'ExecResult', fields:[{name:'stdout',type:'string'},{name:'stderr',type:'string'},{name:'code',type:'int'}], inits:[] },
    { name:'RegExp', fields:[], inits:[] },
    { name:'RegExpMatch', fields:[{name:'matched',type:'bool'},{name:'value',type:'string'},{name:'groups',type:'string[]'}], inits:[] },
    { name:'TerminalSize', fields:[{name:'width',type:'int'},{name:'height',type:'int'}], inits:[] },
    { name:'KeyEvent', fields:[{name:'kind',type:'int'},{name:'code',type:'int'},{name:'text',type:'string'},{name:'ctrl',type:'bool'},{name:'alt',type:'bool'},{name:'shift',type:'bool'}], inits:[] },
];
